name: Tierverhaltenstherapie Fritsche
favicon: null
layout_spectrum: 0.74429
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#110c09'
    - '#d0cad4'
    - '#457eb5'
    - '#9d1926'
    - '#c17541'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
